#pragma once
constexpr char* frames[] = {
"\n\t\t\t\t              OQ                                     "
"\n\t\t\t\t            QRRRQ									"
"\n\t\t\t\t            R@@@R									"
"\n\t\t\t\t           R@@@R										"
"\n\t\t\t\t          3@@RQ										"
"\n\t\t\t\t         t3R@Q3										"
"\n\t\t\t\t         tQ@@Q										"
"\n\t\t\t\t        OR@@@@										"
"\n\t\t\t\t        Q@@@@@										"
"\n\t\t\t\t       Q@@@@@@										"
"\n\t\t\t\t       Q@@@@@@										"
"\n\t\t\t\t        @@@@@@@										"
"\n\t\t\t\t       3OQR@@@@Q										"
"\n\t\t\t\t       t3OQ@@@@O										"
"\n\t\t\t\t        3QR@@@R3tt									"
"\n\t\t\t\t        3R@@@@@Qt/									"
"\n\t\t\t\t         Q@@@@@@Ot									"
"\n\t\t\t\t         OR@@@@@@O									"
"\n\t\t\t\t         3R@@@@@@O									"
"\n\t\t\t\t         3R@@@@@@Q									"
"\n\t\t\t\t         tQ@RQRR@RO									"
"\n\t\t\t\t         tORRROQQRQ									"
"\n\t\t\t\t         OQQQROQ3QQ3									"
"\n\t\t\t\t         3OOQQOOOOO3t								"
"\n\t\t\t\t         t3OOOOOQOO33t								"
"\n\t\t\t\t         3O3ttttOORRR@Q3t							"
"\n\t\t\t\t         QRRQOOOOORRRRRQQQQ							"
"\n\t\t\t\t        OQR@RRQQQQQQQQRQRQQO							"
"\n\t\t\t\t        QRR@@@@@RRQQOQOQRRQOOOO3tt              //t	"
"\n\t\t\t\t       Q@@@@@@R@@@@@@RQQQRQRQO333t((          //^^/	"
"\n\t\t\t\t      OR@RR@@RR@@@@@@@RRRRRQOOOOttt((        /^////	"
"\n\t\t\t\t      tQRRQQRRRR@@@QQR@@@@@QOOQ3(/t33tO3tO3tt//ttt(	"
"\n\t\t\t\t      (ORRQRR@Q@@@QOQR@@@@@RQOQO3t3OOtt3t33tt//t33(	"
"\n\t\t\t\t      QR@RR@@RQ@@Q3OR@@@@@@@QOOQRQQO3t^/O33Ot(^/t3t	"
"\n\t\t\t\t      QR@@@@@QR@R33R@@@@@@@Qtt3QO3O3t^^/t33O3t/^^^/	"
"\n\t\t\t\t      QQ@@@RRRR@QOQR@@@@@RRQtttO3(///^^/ttt33t/^^^/	"
"\n\t\t\t\t      3Q@RR@@RQRR@@@@@@RRR@@O(////^^^^///t/tO3((/^	"
"\n\t\t\t\t       OQR@@@ROQ@@R@@@RR@QQR3(//t3((/(tOOQttt//QQt^	"
"\n\t\t\t\t       OQQ@@@ROORRQQ@RR@ROQRO((t333t/tORQR3((/(QQO^	"
"\n\t\t\t\t        QQRRRQQQQ@RQQQ@RQOQROO33tt3ttt333Q3^(/(t(tt	"
"\n\t\t\t\t        ORRQQOQ@@@@@OORQQORRRQO3t3O3OOO3(((t3(t/(t	"
"\n\t\t\t\t        ORRQOOQ@@@@@OOROQQR@@RQO3OOOOOO3((((OOO^/(	"
"\n\t\t\t\t        ORQOO3Q@@@@ROQ@OQQQOQQRQOOOQQO3(/ttt3RO/^	"
"\n\t\t\t\t        ORQ3t3ORR@@QOQ@QOOQ3QRRQQQOQRQO3tt3QQO3t		"
"\n\t\t\t\t       3QQQO3tt3OQO3Q@QQOOQO3ORQOQQQQOQO3ttO3		"
"\n\t\t\t\t       3QROOQ3tt3OO3ORRRQQOQQOOQR@RQQ3O33t3t			"
"\n\t\t\t\t       3QRQOQQ3t3333OR@@QOOOOOOQQ@@RQOOO333t			"
"\n\t\t\t\t       tOQQQQ@RRQ3tt3OR@QOOOOOOOQQQOOO3tttt			"
"\n\t\t\t\t       (t3OQRRRQO3t (t3RRQQOOOOOOO33O3ttt			"
"\n\t\t\t\t       (ttt3OOOO3    /tQRQR@@RRRQQO33tttt			"
"\n\t\t\t\t       /t33tt33t     /3QR@@@QQQOO333t3tt				"
"\n\t\t\t\t       /(tt333tt     /3OQ@@RQQRQQO333tt				"
"\n\t\t\t\t       (t33tt((      (333333OQRQR@QQO3				"
"\n\t\t\t\t       tt(tt//(      (33333OO3333QQO3				"
"\n\t\t\t\t       t((////(      t3O3QQQO3ORRO33t				"
"\n\t\t\t\t        ((///^/       3OOQR@@@@R@@Q(					"
"\n\t\t\t\t        t(///^^/       OQORRO3t((tOt					"
"\n\t\t\t\t        t(////^^         OQQ3(/^^^(3					"
"\n\t\t\t\t         t//(((/^/         t((/^ ^^(					"
"\n\t\t\t\t         3t(Ottt(t         t/OQOt^^ (				"
"\n\t\t\t\t          33O33O3O         t/QRQt/^ ^				"
"\n\t\t\t\t                           3ttt(tOO/^^				"
"\n\t\t\t\t                           O33ttt33/^^				"
"\n\t\t\t\t                             O3///t3t^(				"
"\n\t\t\t\t                              3//(/t(//t				"
"\n\t\t\t\t                              O(/(^t(/((O			"
"\n\t\t\t\t                               33O3O3333O			",
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
"\n\t\t\t\t         QQ                                          "
"\n\t\t\t\t        ORQQ											"
"\n\t\t\t\t       QRRRQ											"
"\n\t\t\t\t       @@@@											"
"\n\t\t\t\t      R@@@@											"
"\n\t\t\t\t     Q@@@@											"
"\n\t\t\t\t     Q@@@Q											"
"\n\t\t\t\t     3R@@t											"
"\n\t\t\t\t    33Q@RQ											"
"\n\t\t\t\t    3O@@@@											"
"\n\t\t\t\t    R@@@@@											"
"\n\t\t\t\t    @@@@@@											"
"\n\t\t\t\t    @@@@@@@											"
"\n\t\t\t\t    R@@@@@@@											"
"\n\t\t\t\t     @@@@@@@Q										"
"\n\t\t\t\t     OQQR@@@QO										"
"\n\t\t\t\t     3OQ@@@@Qtt/										"
"\n\t\t\t\t      OR@@@@R3(/										"
"\n\t\t\t\t       Q@@@@@@@O										"
"\n\t\t\t\t       3R@@@@@@@										"
"\n\t\t\t\t       tQ@@@@@@@t									"
"\n\t\t\t\t       tQ@@@@@@@O									"
"\n\t\t\t\t        3@@@R@@@RO									"
"\n\t\t\t\t        3QRRQOQOQQ3									"
"\n\t\t\t\t         QQQRQQ3OQ33									"
"\n\t\t\t\t         3QQRQO33QO3									"
"\n\t\t\t\t         3OOOQQQQOOQO(								"
"\n\t\t\t\t         Ot((t33QRRRRQ33O							"
"\n\t\t\t\t        OQO33t33QQQQQQQQQQ3                       ^	"
"\n\t\t\t\t        Q@RRRRRQQOOOO3ORQQO3OO33((             (^((	"
"\n\t\t\t\t       QR@@R@R@@@@@@@RRQRRQQOO333tt(          ^^^//	"
"\n\t\t\t\t       RR@@@@R@@@@@@@RRRRRQO3O33ttt(/        ^^(//^	"
"\n\t\t\t\t      Q@@@RRRQR@@@QOR@@@@@@QOOQ3//t33/33tOttt/(tt3t	"
"\n\t\t\t\t      Q@RRQRRQ@@@Q3OR@@@@@@@QOQ3tt3OOtttt33tt/(t33(	"
"\n\t\t\t\t      tQ@R@@RQR@Q3OR@@@@@@@@OO3Q@QOO3(//Ot3Ot/^/(3t	"
"\n\t\t\t\t      @@@@@@RR@R33Q@@@@@RQRQtt3QO3O3(^^/tttOtt/^ ^/	"
"\n\t\t\t\t      R@RR@RRR@RRR@@@@@@QQRQtttQ3//^^///tt3t3(/^^^/	"
"\n\t\t\t\t      QR@@@@ROQR@@@@@@RR@@@@3///^/^^^//^/t/tOt//^	"
"\n\t\t\t\t      tRRR@@Q3QRRQQR@R@@RQQR3//^tt///(3QRQt3t((OOt^	"
"\n\t\t\t\t      3RRR@RQ3OQQQOQ@R@RQOQRO(/(3OOt/tORQR3t(//OQO^	"
"\n\t\t\t\t       RQRRRQQRR@@@RORRRQOQRQO33tt33t(3OOQ3^(/(//(t	"
"\n\t\t\t\t       RRQRQOQ@@@@@QOROOQQR@RO33t3OOOOOO(((tt//(((	"
"\n\t\t\t\t       QRRQQQR@@@@@OO@Q3QQR@RROO33OOOQQ3tt(/QQO^^t	"
"\n\t\t\t\t       3@ROOOR@@@@QQQ@QQQQO3RORQO3QQOO3/(ttttR3(/t	"
"\n\t\t\t\t      tQRQO33QRRRQOQ@RQOOQQ3RRQOQOOQRQO3tt3QQROt		"
"\n\t\t\t\t      3QRQOtt3OOQO3ORRROQOQOOQ@QOQQQOOOO3t33t		"
"\n\t\t\t\t      3RQQQ3((t33OOQR@@QOOOOQQQR@@RQO3O333333		"
"\n\t\t\t\t      3QQOOOt((t3OOOQ@@R3QO33QQR@@@RQQOO3333			"
"\n\t\t\t\t      3QRQOQQO33ttt3OQ@QO333OQOQQRQOO33t333t			"
"\n\t\t\t\t      t3QRQQR@RRQ33tt3QRQRRRQQRQQQQO3tt33O			"
"\n\t\t\t\t      ttOQRR@@@R     3RRR@@@@@@@RQQO3ttttt			"
"\n\t\t\t\t      (3tt33OQ        3R@ROOO33333t33OO3t			"
"\n\t\t\t\t      /ttt33QO         O@QQRRRQOO33OQO3t				"
"\n\t\t\t\t      /333OO3t         3tt33ORR@@QR@ROO3				"
"\n\t\t\t\t      ttt333(           QQQO3333Q@@@RQ3				"
"\n\t\t\t\t      (((ttt(           R@Q3OQRRQRQO3tt				"
"\n\t\t\t\t      t(/(tt(t          3@@@@@@@@RO3t(/				"
"\n\t\t\t\t      t(((((//           ORO3t((3Ot3t((				"
"\n\t\t\t\t       (((/(/^           t3t(//^/tttttt				"
"\n\t\t\t\t       t/((((//          ttt(/^/^/tt3(				"
"\n\t\t\t\t       3/(OtOt(/          ORRQOt(^/t33				"
"\n\t\t\t\t        3(Ot3333           Q@@Ot/^^(					"
"\n\t\t\t\t                            tttOQ3^^					"
"\n\t\t\t\t                            3tt33(^^3				"
"\n\t\t\t\t                            O//(t3t^(				"
"\n\t\t\t\t                            O((t(tt(/3				"
"\n\t\t\t\t                            Ot((^tt(t(O				"
"\n\t\t\t\t                             Ot33333t3Q				",
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
"\n\t\t\t\t   OOQR                                              "
"\n\t\t\t\t   OQRR												"
"\n\t\t\t\t   QR@@												"
"\n\t\t\t\t   @@@@												"
"\n\t\t\t\t   @@@@												"
"\n\t\t\t\t   @@@@												"
"\n\t\t\t\t   Q@@Q												"
"\n\t\t\t\t   3R@Q												"
"\n\t\t\t\t   Q@@@@Q											"
"\n\t\t\t\t   @@@@@R											"
"\n\t\t\t\t   @@@@@@											"
"\n\t\t\t\t   @@@@@@											"
"\n\t\t\t\t   @@@@@@R											"
"\n\t\t\t\t   Q@@@@@@R											"
"\n\t\t\t\t   3OQQ@@@R3t										"
"\n\t\t\t\t     OQ@@@Q3t(										"
"\n\t\t\t\t     QR@@@@Q3/										"
"\n\t\t\t\t     3R@@@@@@RO										"
"\n\t\t\t\t       @@@@@@@O										"
"\n\t\t\t\t       R@@@@@@O										"
"\n\t\t\t\t       Q@@@@@@Rt										"
"\n\t\t\t\t       O@@@@@@@Q										"
"\n\t\t\t\t       3O@RQOQORO									"
"\n\t\t\t\t       OORRQ3O3QQ3									"
"\n\t\t\t\t         QQRQO3OQOt									"
"\n\t\t\t\t         OOO3OOQQQQ3t								"
"\n\t\t\t\t         3ttt3OQQQRO333								"
"\n\t\t\t\t         O33OOQQQOOQQQRQQ33                     /(t	"
"\n\t\t\t\t       QQ@R@R@@@@@@RRQRQRQOO3O3Ott(         t^^^^(	"
"\n\t\t\t\t       QQRRRR@@@@@@@RRRRRQOQ3O3tt3t/        /^////	"
"\n\t\t\t\t       R@@RQR@@@@QOQ@@@@@RQQOOOt//33(tOt3tt3/(t3tt	"
"\n\t\t\t\t     QR@RRRRQ@@@Q3OQ@@@@@@RQOQOtt3OO3/3tt3t(//t33t	"
"\n\t\t\t\t     OQ@RQR@QR@QtOR@@@@@@@RRO3Q@RQOOt(/3O3O3(^/(Ot	"
"\n\t\t\t\t     3O@R@@RR@ROOR@@@@@RORQ33tOQOOO3/^/(OtO33^^^^/	"
"\n\t\t\t\t     R@@R@@RR@RR@@@@@@RQORQOttOQ((/^^^^(t333t/^^^(	"
"\n\t\t\t\t     RRR@@@ROQR@@@@@@Q@@@@@Rt/(///^^^^^^t/tOt((^^^	"
"\n\t\t\t\t     3Q@R@@Q3QQQOOR@R@@@QQ@Q(/^/t(///(3OOt3t((OOt^/	"
"\n\t\t\t\t     (Q@R@RQOQQRQ3RRR@RROQROt/(tO33((OQRO3t(//OR3^/	"
"\n\t\t\t\t     3QRRRQQR@@@@@QO@RRQOQRQO333t3tt/tOQ@Q/((^(((t	"
"\n\t\t\t\t     RRQQQQOQ@@@@@OQ@3OQQR@RQOO333OO3O33/(tt^//((O	"
"\n\t\t\t\t     QRRRQOQR@@@@ROQ@OOQRQ@RQQO333OOQQQ3t(t3O3///O	"
"\n\t\t\t\t     3R@QO3O@@@@RQR@QQQQQQOROQQOOOQOOOt/((((RO//(3	"
"\n\t\t\t\t     3R@QOOOQQRQ3OR@QOOQQR3RQOOOOOORQO3t(3OQROt(		"
"\n\t\t\t\t     ORRQtt3O3QOO3Q@RRQQQQOORROOQQQOOOO3t3O3tt		"
"\n\t\t\t\t   ttORQQt((tt3OOQQR@@OQOOOQQQR@@RQOOOO3OO3333		"
"\n\t\t\t\t   ttQRQQ3//(t33O3OQ@@OOQO3OQR@@RRRQQQOOO3O3			"
"\n\t\t\t\t   ttQQQ3Q3t(ttt3t3OQRQQO33QQQQQQQQ3333OQ3t3			"
"\n\t\t\t\t   ((3QQQRRQQO33ttttQ@QQ@@RRRRQRROO333OOOQ			"
"\n\t\t\t\t   t(3ORQQRRRR      OR@@@@@RR@RQRQO33333tt			"
"\n\t\t\t\t   t/3tt3OQQO        3R@QQOO3OO3OQOQQ@RQOt			"
"\n\t\t\t\t   t/tttt33t         t3OOQR@RRO3OR@@@@RQ33			"
"\n\t\t\t\t   3/33tt((          tO3OOOOQQR3  @@@@@@ROtt			"
"\n\t\t\t\t   t((ttt/(          (Q@ROOOOQO     @@@Qt^/(			"
"\n\t\t\t\t   3(((((^(          /OR@RRR@@R     @@ROt/^/			"
"\n\t\t\t\t     ///(^/           (RRR@RRR@      OQQO(^^			"
"\n\t\t\t\t     ((//^^           //3ttt(/t3      3O3t/(			"
"\n\t\t\t\t     (((/^^           (/tt((///t       33t((			"
"\n\t\t\t\t     t/(((/^(          ^(Ot((/^/       t3(t3			"
"\n\t\t\t\t     3/t33t/(          (/QRR3t/^/     333t//			"
"\n\t\t\t\t     Ot3O33t3          t3OOOtt/^^    t333Ott			"
"\n\t\t\t\t                         Q(3OQO(^(  33QOQO			"
"\n\t\t\t\t                         O(t333/^( OOOOQQ3			"
"\n\t\t\t\t                          (/t333/(O3OOO3t			"
"\n\t\t\t\t                          t(ttt3t(3Q					"
"\n\t\t\t\t                          t/t/tttt(Q					"
"\n\t\t\t\t                          OtO333333Q					",
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
"\n\t\t\t\t   QQ                                                "
"\n\t\t\t\t  OQRRO												"
"\n\t\t\t\t   R@RQ												"
"\n\t\t\t\t   @@@R												"
"\n\t\t\t\t  R@@@Q												"
"\n\t\t\t\t  Q@@@Q												"
"\n\t\t\t\t   OQ@Q3												"
"\n\t\t\t\t   3Q@@@R											"
"\n\t\t\t\t   O@@@@R											"
"\n\t\t\t\t   @@@@@@R											"
"\n\t\t\t\t   @@@@@@@											"
"\n\t\t\t\t    @@@@@@@											"
"\n\t\t\t\t    @@@@@@@R											"
"\n\t\t\t\t    QR@@@@@@O										"
"\n\t\t\t\t     3OQ@@@@O3t										"
"\n\t\t\t\t     3QR@@@@Q3/t										"
"\n\t\t\t\t      Q@@@@@@Ot3										"
"\n\t\t\t\t       Q@@@@@@@3										"
"\n\t\t\t\t       O@@@@@@@3										"
"\n\t\t\t\t       3@@@@@@@3										"
"\n\t\t\t\t       tQ@@@@@@R										"
"\n\t\t\t\t        OR@RQ@@ROO									"
"\n\t\t\t\t         QRRQ3OOQO									"
"\n\t\t\t\t         OQQRRO3OOtt									"
"\n\t\t\t\t         3OQQOOOOO33									"
"\n\t\t\t\t         333tt3OQQQQO3                           ^	"
"\n\t\t\t\t         OOO3OQQQOOOOOQQQQ3tO33t               ^^(3	"
"\n\t\t\t\t         QRRQQRRRRRQQO3QRRQOOOOO3(            ^^^((	"
"\n\t\t\t\t        QRRRRR@@@@@@RRRRRRQO3OOttttt       t(//////	"
"\n\t\t\t\t       QRRRRRQ@@@@RQRR@@@RQO3OOt/((t/    3(t(/((((/	"
"\n\t\t\t\t      Q@@RRRRQR@@OtOR@@@@@RQOQQ3ttOO3(3t33tt//t33tt	"
"\n\t\t\t\t      QRRQR@@RRR33O@@@@@@@@Q33QRQRQOt//3OtO3(/^/t(t	"
"\n\t\t\t\t     tO@RR@@@QRQOOR@@@@RR@@Q33OROOQ3(^/tOtO3t/  ^/t	"
"\n\t\t\t\t     Q@R@@@@@OQR@@@@@@RRQ@RQtt3Ot/^^/^^(t(tO3//^^^/	"
"\n\t\t\t\t     QR@@@@@QOQRRQR@@R@@@@@Rt////^^^^///t(/33/tt(^^	"
"\n\t\t\t\t     OR@@@@@Q3QQQ3Q@@@@@@R@Qt(/^((^^/(t33tttt/tO3/^	"
"\n\t\t\t\t     t@RR@@RQQQRRQQQR@@RQQRQ3(t33O3((OQRQQ((/^OQO(/	"
"\n\t\t\t\t     QRQRRRQOR@@@@QQRQRQQQRROO3tt333(t3333(//^(^(33	"
"\n\t\t\t\t     @ROQQQOOQ@@@@QQ@3QQQQRRQO33t33333tt//tt(^(/(33	"
"\n\t\t\t\t    O@@RRQOOQ@@@RQQRR3OQRRRQOQOOOOOOOO3((((tRQt^^3	"
"\n\t\t\t\t    3@@@QOOOQ@R@OQRRQOOQQRQQ3QQOOOOOO3t/(t((QR(^^	"
"\n\t\t\t\t    3R@RO3333QOO3O@RQOOQQQ3RQO3OOOOQROO333OQQOt(		"
"\n\t\t\t\t   3QR@R3t(t333OOOR@@QOQQQO3QROOOQQOOOO333QOt33		"
"\n\t\t\t\t   3QRRROt/(tt3O3OR@@QOQOOQOORRQQQQOOOO3OQQ33O3		"
"\n\t\t\t\t   3QRQQOt(/((t333OQ@ROQQQOQQRRQQQQQQRRQQQO333		"
"\n\t\t\t\t  (tORQQQQO3tttttt3OR@RQOOOOOOOOQOOQOQRRQO3OQ3		"
"\n\t\t\t\t  /t3QQQQRQRO3tttt3OR@RRRRR@RQRQOO3OOQQRRRQRRO		"
"\n\t\t\t\t  /ttt3OOQQO3       OR@RQ33OOOQQQQOQQQQQO333OO		"
"\n\t\t\t\t  /t33t333Ot        3ORQRRO3OOQQQQQQRR@@@RQ33t		"
"\n\t\t\t\t  /t3ttt(t          OO3OOQ@@RQQO    @@@@@QQQQO		"
"\n\t\t\t\t  ((ttt(/           tR@ROOOQQR       @@@@@@O/^^(		"
"\n\t\t\t\t  ((ttt(/           (Q@QOOORRQ       @@@@@Rt/^^^		"
"\n\t\t\t\t  t((((//           /3@R@@@@@@        R@RQO3(^^ ^	"
"\n\t\t\t\t  t/(((/^/          //3O3QQQQR          O(tt//^//t	"
"\n\t\t\t\t  t/((//^/          /^tttt333O          3((/^^^/tt	"
"\n\t\t\t\t  3((((/^^          /^^33tttt3            (/^^^^^(	"
"\n\t\t\t\t   ((OttO^          (  3@RO33(             ^^^^tt(	"
"\n\t\t\t\t   3/Ottt(((        t^^(QRO33//3           ^^^^/^	"
"\n\t\t\t\t     OOOO           3^^^t3OQQ3/t           /(tt33	"
"\n\t\t\t\t                    3/^^(3ORR3^t           tttt33	"
"\n\t\t\t\t                      3Q(t33O3(3          O(/(//t	"
"\n\t\t\t\t                      QOtt3t333t          3(tt//t	"
"\n\t\t\t\t                      OOt(t(33tttO        3ttt/(		"
"\n\t\t\t\t                        OtO3OO3O3Q         OO33		",
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
"\n\t\t\t\t   OO                                                "
"\n\t\t\t\t  RRR												"
"\n\t\t\t\t  @@@												"
"\n\t\t\t\t  @@@												"
"\n\t\t\t\t  R@@O3												"
"\n\t\t\t\t  Q@@Ot												"
"\n\t\t\t\t  3O@QQ												"
"\n\t\t\t\t  3@@@@												"
"\n\t\t\t\t  Q@@@@												"
"\n\t\t\t\t  @@@@@@R											"
"\n\t\t\t\t  @@@@@@@											"
"\n\t\t\t\t   @@@@@@@Q											"
"\n\t\t\t\t   QQRR@@@RO3										"
"\n\t\t\t\t   OOQR@@@RO3										"
"\n\t\t\t\t   33QR@@@R3t										"
"\n\t\t\t\t     Q@@@@@R3/t										"
"\n\t\t\t\t     Q@@@@@@R33										"
"\n\t\t\t\t     3Q@@@@@@RO										"
"\n\t\t\t\t     tO@@@@@@@3										"
"\n\t\t\t\t     tO@@@@@@@O										"
"\n\t\t\t\t       R@@QRR@@										"
"\n\t\t\t\t       QR@ROQQQQ3									"
"\n\t\t\t\t       OQRQROO3OO3									"
"\n\t\t\t\t       3OOOOOOOOOOt3									"
"\n\t\t\t\t       3OO3t3333OQOQQOt								"
"\n\t\t\t\t       OOOQO3333OQRRRRQO3                      ^/t	"
"\n\t\t\t\t       QQR@@@RRRRRQOQOOOQQRO3O333(            ^^/(	"
"\n\t\t\t\t       QR@@@@@@R@@RRQQQOOQQQ3O33tt          (^///(	"
"\n\t\t\t\t       @@@@@@@RR@@@@RRRRRRRQOO3(/tt/(O  3ttt^/((((	"
"\n\t\t\t\t     QR@@@@@@RQR@@@RQQRRRRRQOQ3t/3O3(33t3ttt//t3tt	"
"\n\t\t\t\t     OR@@QQRQRRR@R33QR@@@R@QOQQRO3O3t(/O33Ot/^(t3(	"
"\n\t\t\t\t     3Q@RQR@@@RRR33Q@@@@@@@O33QQQQO3/^(Ot3Ott^ ^/t	"
"\n\t\t\t\t     OR@@RR@@@RRROQR@@RRR@R333OQ33t(///tt333t/^^^t	"
"\n\t\t\t\t     @RQ@@@@@ROQR@R@@ORRR@R3t(t(//^//^^/t/tQt//^^^	"
"\n\t\t\t\t     Q@@@@R@RO3OQ3Q@R@@@@@@3(///(^^^((3OOttt(/OO(^t	"
"\n\t\t\t\t     3@@R@@@RO3OQ3ORR@@@RRRO///tO3t(tOQQR33(/^ORt^(	"
"\n\t\t\t\t     Q@R@@@RQOR@@@QQ@RRRQRQO33O3333(/OQQ@Q^((/(//(	"
"\n\t\t\t\t     @QORRRQOO@@@RQROQRRQRRQO333333O333t/(t3(^(/33	"
"\n\t\t\t\t     @QQQRRQ3QR@@QQR33RQRRRQQO333OOOQQO((((OO3(^(	"
"\n\t\t\t\t   (3@@@RQQOQR@@QRRQO3QRRRQ3QQQOOQOOO3t/((((OQ/^		"
"\n\t\t\t\t   t3@@@ROOOOQRRORROQOQRROOtOQOOOQQQQO3(t33OQQt(		"
"\n\t\t\t\t   OQR@ROt333OQOOQ@Q33QQQOOQOt3OOQOQQOO333OO3t		"
"\n\t\t\t\t  (QRQRROt((t3O33Q@@QQQRQQ3OQQOOOQOQOOO3QQQ3tt		"
"\n\t\t\t\t  tQRRQRQ3(/(tt33O@@Q3QQO3OOQRRRQQQRQQQRRQO3OO		"
"\n\t\t\t\t /3OQRQOQO3t(((tt3Q@RQQOOOOOOOO33QQRRQRQQQO3O3		"
"\n\t\t\t\t ^t3OQRQRRRQOttt33OR@RRRQQQOQOOO3QOQRRRQQOO333		"
"\n\t\t\t\t /tt33QQQRRQO    OOQRRRQQQQOQROO3OOQQQQQQQRQQO		"
"\n\t\t\t\t (333t333        3O3OQRRQ333OOOOOQQQQQRRROOQRQ		"
"\n\t\t\t\t (333ttt3        t3O3OQRRQOOOQQOQQQOQR@@@RQQRQ		"
"\n\t\t\t\t (ttt(/          (3QRROOQRRQO3    QOQR@@R3((t3		"
"\n\t\t\t\t ((t3(/          ^(O@RQQQQRQ3     33R@@ROO33t3		"
"\n\t\t\t\t (tt3(/          /(3R@@@@@@R        R@@RQRQOQO		"
"\n\t\t\t\t (ttt(/          ^/(3OQRRRQO        QQR@@R3/^/		"
"\n\t\t\t\t (t3t(/^3        ^^^t3333t(t        3ORRR3(^ ^^(		"
"\n\t\t\t\t t3ttt/^t        ^^^(Q3t3t((          RO3t(^^ ^^		"
"\n\t\t\t\t  O3t3t/3        / ^^3RROO(/t         3t//^^^^^(		"
"\n\t\t\t\t   OO            t ^/(3OOO3/(           3^^^^^^^		"
"\n\t\t\t\t                 t^^/(3QRRO/(           3^^^^^^/		"
"\n\t\t\t\t                  (^3(tt3O3tt             ^^^^^^		"
"\n\t\t\t\t                  3tQ/3OOQO(t             (^^^^/		"
"\n\t\t\t\t                    O(3t3333t3            O3t(^ ^(	"
"\n\t\t\t\t                    Ot3t3OO33O              R3t(t^/	"
"\n\t\t\t\t                    Q3RQQQOO3Q              @Q3Ot/^	"
"\n\t\t\t\t                                              R@RO(	",
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
"\n\t\t\t\t   OQQQ                                              "
"\n\t\t\t\t   ORRRO												"
"\n\t\t\t\t   R@@@Q												"
"\n\t\t\t\t    @@@RO											"
"\n\t\t\t\t    Q@@R3											"
"\n\t\t\t\t    3ORR3											"
"\n\t\t\t\t   t3Q@@@											"
"\n\t\t\t\t   3Q@@@@											"
"\n\t\t\t\t    @@@@@											"
"\n\t\t\t\t    @@@@@@@											"
"\n\t\t\t\t     @@@@@@											"
"\n\t\t\t\t     QR@R@@@Q										"
"\n\t\t\t\t     QQQR@@@Q										"
"\n\t\t\t\t     33O@@@@Ot(										"
"\n\t\t\t\t      OR@@@@Rt/										"
"\n\t\t\t\t      3R@@@@@Qt										"
"\n\t\t\t\t      tO@@@@@@@										"
"\n\t\t\t\t       tR@@@@@@										"
"\n\t\t\t\t       tR@@@@@@										"
"\n\t\t\t\t        Q@@RRR@QO									"
"\n\t\t\t\t        OR@RQORQQ									"
"\n\t\t\t\t        3QQRQOO3Q									"
"\n\t\t\t\t        3OQQQO3OOOOt									"
"\n\t\t\t\t        tOOOOOOOOOO333								"
"\n\t\t\t\t        3QO3O33ttt3OQRRRRQ3							"
"\n\t\t\t\t         RRR@@@@RQQQOQR@@@QO3						"
"\n\t\t\t\t         R@@@@@@@@@RRQOQQRRRQO						"
"\n\t\t\t\t        R@@@@@@@@@@@@@RRQQOQQRQO/(              ^/(	"
"\n\t\t\t\t       O@@@@@@@@@RRR@@@@RRQQQOOO33(/          ^^///	"
"\n\t\t\t\t       OR@@RRR@@RRRR@@@RRRRRQO3O3ttt        t/^////	"
"\n\t\t\t\t      ((O@@ROQRRRRQ@@RO3QR@@@OOO(/(33/3O333t3//ttt(	"
"\n\t\t\t\t      (tOR@RQ@@@@RR@R33ORR@@@OQOt(tOO3(Ot33t(/(t3tt	"
"\n\t\t\t\t      O@@@R@@@@@@RRRt3R@@@@@@OOQRROOO3(/tOt33/^^(O(	"
"\n\t\t\t\t      Q@R@@@@@@@RQQQRR@@@@@@Q33OQQQQO(/^(Ott3t( ^^^	"
"\n\t\t\t\t      ORR@@@@@@@ROQR@@@@RQ@@Qtt3Ot3t(///(tt33t/^^^/	"
"\n\t\t\t\t      33RRQR@@@ROOQQRRQR@R@@Rt(((/^//^/^^tt/33/(//	"
"\n\t\t\t\t       OQOR@@@RQQQRQQQ@@@@@@Qt(/(tt///(3OOQtt(/3R3/	"
"\n\t\t\t\t       OROQR@RRQQR@RQR@@@@@@Ot(/t33t((3O@QRtt/^3RO(	"
"\n\t\t\t\t      tORRQRRQQOQ@@@QRRRRQQROO333333t((3OOQ3///(/t(	"
"\n\t\t\t\t     t3OR@@RRQQQRRRQRQORQQQRQQOO3333OOOO3(((tt((/(t	"
"\n\t\t\t\t    t3OOR@@RQQOORRQQRO3RRQRQQQQO333OOOOO3(((tQOt^/t	"
"\n\t\t\t\t   (t3QRRRQOOO3OQO3QQO3QRRRQ3OQOOOOOOOO3(/(ttORt^^	"
"\n\t\t\t\t   (33QRRQQO3333OO3QQQOQRQOQtOOOOOOQQQQO3tt3OQQ3(	"
"\n\t\t\t\t  ^(33ORQQRQ3t((333QROOQQQ3O@OttOQQQOOQOOOO3O3t3		"
"\n\t\t\t\t  ^(333RRQ3QQOtttt3R@3QRRQQ33QROOOOOQQOOOOQQ3t33		"
"\n\t\t\t\t  /33333QQOQRQO33t3Q@O3QQO3OOORRRQQQOOOOORROtOO3		"
"\n\t\t\t\t  (t33t3333      3OQ@QQQOOOOOOO33OQQRQQQQRQQOO3		"
"\n\t\t\t\t  ((t3OOt        3OORRRRRQQO333O3QOOQQQQQO33t3		"
"\n\t\t\t\t  (tt3O3t        tOOQ@@RQQQOQQQO3OOQRQQRRRQQQ3		"
"\n\t\t\t\t  (((t33t      (^/3Q3OQRRQ33OQO33OOOOQQQOtt3R3		"
"\n\t\t\t\t  ((t33Ot      /^/tQQQOQRRQ3OOOOOOOOOR@@@ROtQ		"
"\n\t\t\t\t  tt(333t      (//(3@RRQOQQQ3     OOR@@@QO333		"
"\n\t\t\t\t   (t3333      (^/((OQ@@@@RO        @@ROt(((/		"
"\n\t\t\t\t   /tO333      t^//(t3QQQOO3        @RROO33t(		"
"\n\t\t\t\t   (3O3Ot      t^^^/Ot333tt         QR@@@RQRO		"
"\n\t\t\t\t     33O3        ^^/3QOO3(/         RRRQt///3		"
"\n\t\t\t\t       3         ^^/tOOOO(/         RQQ3(^^^3		"
"\n\t\t\t\t                 ^^((3QRQ3(         3ttt/^^ /		"
"\n\t\t\t\t                 ttO(3OQQ3(         t/// ^^^/		"
"\n\t\t\t\t                 OOOtOQRQ3(3        3// ^/^((		"
"\n\t\t\t\t                   33t3QOQt3          ^^^^/3t		"
"\n\t\t\t\t                   O3t3O3O3O          ^^ ^^/t		"
"\n\t\t\t\t                      OOQQO           /^^  /t		"
"\n\t\t\t\t                                      (^^/((///(		"
"\n\t\t\t\t                                      3/(/^/3//^(	"
"\n\t\t\t\t                                      OO3O33O3Ot/	",
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
"\n\t\t\t\t    OOQRO                                            "
"\n\t\t\t\t    O3QRR											"
"\n\t\t\t\t      R@@											"
"\n\t\t\t\t      @@@											"
"\n\t\t\t\t      @@@R											"
"\n\t\t\t\t      @@@R											"
"\n\t\t\t\t    3OOR@Q											"
"\n\t\t\t\t    3t3O@Q											"
"\n\t\t\t\t    333O@@R											"
"\n\t\t\t\t    QR@@@@@											"
"\n\t\t\t\t    Q@@@@@@											"
"\n\t\t\t\t      @@@@@@											"
"\n\t\t\t\t      @@@@@@											"
"\n\t\t\t\t      R@@@@@@										"
"\n\t\t\t\t      OQQ@@@@O										"
"\n\t\t\t\t      33Q@@@@O3										"
"\n\t\t\t\t      3O@@@@@3((										"
"\n\t\t\t\t      3O@@@@@Qt										"
"\n\t\t\t\t      (O@@@@@@QO										"
"\n\t\t\t\t      (O@@@@@@@										"
"\n\t\t\t\t        @@@@@@Rt										"
"\n\t\t\t\t      (3@@@@@@Q3										"
"\n\t\t\t\t      (t@@RR@@@Q										"
"\n\t\t\t\t        Q@RQQRRQ										"
"\n\t\t\t\t        QQQRQO3Q3									"
"\n\t\t\t\t      (tOOQQOOOOO3									"
"\n\t\t\t\t      (tOOOOOOOOOO3									"
"\n\t\t\t\t      t3OOOQQO3tt3OOQQQ								"
"\n\t\t\t\t      3OR@@@@@@RRQQOQRR@@Q3							"
"\n\t\t\t\t      3Q@@@@@@@@@RRQQQQRRQQ							"
"\n\t\t\t\t      Q@@@@@@@@@@@@@RQQQOOORQO3                  /	"
"\n\t\t\t\t      R@@@RRR@@RRR@@@RRRRQQQROO3(             (^/tt	"
"\n\t\t\t\t    33QRRQQOQQQQRR@@@@RRRQRRQOOO3(/         3^^^//t	"
"\n\t\t\t\t    /(3O@ROQ@R@RQ@@Q33QR@@@QOOO3ttt((     (/(/(((/	"
"\n\t\t\t\t    (33Q@RQR@@@QQRRttQR@@@RROQO(((tt/33tO333(/(tt(	"
"\n\t\t\t\t    3Q@RR@@@@@RQRR3OR@@@@@@QOQQ3t3OQ3ttt33tt(^(3Ot	"
"\n\t\t\t\t    Q@RR@@@@@@QRRQRR@@@@@@@RO3Q@@QOO3t/3OtOOt^^/((	"
"\n\t\t\t\t    QRQRR@@@@@QOQR@@@@@@@@@R33QRQRRQ3/^tOtOOt(^^^/3	"
"\n\t\t\t\t    3OOQQR@@@R3OR@@@RQRRQ@RQttOOt//^/^/(t(t33//^ ^(	"
"\n\t\t\t\t    t3QQOR@@RQQQQRQQR@@@@@ROt((///^/^^//tt/33((tt^t	"
"\n\t\t\t\t      QQOR@@RQQRR@QQ@@@@@@Q3t(//(/^^^((333ttt(tQ3^(	"
"\n\t\t\t\t      OQRRQRQOQ@@@QR@@RRQQQ33(t3OO3t(3QRRRtt/^3QO/(	"
"\n\t\t\t\t      3QRQQRQQQ@@@QRORRQQQRQQO333333tt33OO(/(^(^(t3	"
"\n\t\t\t\t      OQRQQQQOR@@@QQ3QRQQRRQQO33333O333t((tt(^(//O	"
"\n\t\t\t\t    ttQQQO3OOOQQQORO3OQRRRQOQQQOOOOOOQQt(((tQQ3^^3	"
"\n\t\t\t\t    33QRQQO3t3OOOORQOQRQQOQtOOOQOOQQQO3/(t(/3Rt(^	"
"\n\t\t\t\t  t(33QQQ3O3tttt33Q33QQQQ3QRQtOOQQOQQQO333QQ33		"
"\n\t\t\t\t  (/33ORQOQRQ3tttOROQRRQRQ3QRRRQQQOQOO33QO3t			"
"\n\t\t\t\t  t/tt3QQOR@RQOttQR33QRQOQOOQ@@RRQQQQQOQQO3O			"
"\n\t\t\t\t  /^(33(33OQQQQQQQRO3OQRQOQQRQOOOQQQQOOQQOtt			"
"\n\t\t\t\t  t/tttt3333(tOQQQ@RQRQO3OOOOOOOQQOOQQQQQOO3			"
"\n\t\t\t\t  (/33t3t33^^tOQQO@@@@RQQRQQRQQOOOQQRQQQQQO3			"
"\n\t\t\t\t  t(//tt(3(^/(3OOQOQR@RRQQQOQQOQQOQQRRRQO3			"
"\n\t\t\t\t   ////((t(^/(tOOROOQRR@RQQOOOOQQQQR@@@RQ3			"
"\n\t\t\t\t    (/^^/((^/(tt3@RQOOQR@RO     R@@@@ROt(t			"
"\n\t\t\t\t    ////^///((((tOR@RRRQQ       R@@@ROOttt			"
"\n\t\t\t\t    (^//////(((((3Q@@@@@R       Q@@@@@R33t			"
"\n\t\t\t\t    t/////^/(((((ttOQQOQO       R@@@@QQRO3			"
"\n\t\t\t\t    t/(((///((((/3tt3tt(3       OQQ3(//(				"
"\n\t\t\t\t    3((t(t/(/t(((33333( 3       333(^^^/				"
"\n\t\t\t\t      3t(ttt(3t33t33Ot((3        ((/^^^^				"
"\n\t\t\t\t        OQO33QQOttORR3(/3        (^^(/(t				"
"\n\t\t\t\t            QRQOt33QQOt(O        ^^^(((O				"
"\n\t\t\t\t              Qt33QR@Q3          /^ /t3t				"
"\n\t\t\t\t               OtOQQRO3          ^^ ^ (t				"
"\n\t\t\t\t                  QQQQQ          /^^//(3				"
"\n\t\t\t\t                                 t/(ttt(/(			"
"\n\t\t\t\t                                 3(t((tt((/O			"
"\n\t\t\t\t                                  OOO3OQO3(3			",
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
"\n\t\t\t\t         ORR                                         "
"\n\t\t\t\t         ORRQO										"
"\n\t\t\t\t         Q@@QO										"
"\n\t\t\t\t         @@@											"
"\n\t\t\t\t         @@@											"
"\n\t\t\t\t         @@@											"
"\n\t\t\t\t         OR@											"
"\n\t\t\t\t        t3Q@OO										"
"\n\t\t\t\t        t3Q@QR										"
"\n\t\t\t\t        @@@@@@										"
"\n\t\t\t\t        @@@@@@										"
"\n\t\t\t\t        @@@@@@										"
"\n\t\t\t\t        @@@@@@										"
"\n\t\t\t\t        Q@@@@@										"
"\n\t\t\t\t        3OQR@@@Q										"
"\n\t\t\t\t        t3Q@@@@O										"
"\n\t\t\t\t         Q@@@@Qt((									"
"\n\t\t\t\t        3@@@@@@3(t									"
"\n\t\t\t\t         Q@@@@@Q33									"
"\n\t\t\t\t        3Q@@@@@@										"
"\n\t\t\t\t        O@@@@@@@										"
"\n\t\t\t\t        OR@@@@@@										"
"\n\t\t\t\t        3R@@R@@@										"
"\n\t\t\t\t        3Q@RQR@ROO									"
"\n\t\t\t\t        OQQQO3OOQ3									"
"\n\t\t\t\t       t3OOQQOOOO3									"
"\n\t\t\t\t       t33OQOOOOQO									"
"\n\t\t\t\t       3OO33OO333333									"
"\n\t\t\t\t       OQOQR@RRQO3O3ORQQQ							"
"\n\t\t\t\t      3Q@@@@@@@@RRRQQOQQRQ3							"
"\n\t\t\t\t      O@@@@@@@@RRRR@@RRQO3OQQ                    ^(	"
"\n\t\t\t\t     Q@@@@@@R@RRQR@@@@RRRQQQROO3t              ^/(t	"
"\n\t\t\t\t     Q@@@@RQQRRQQR@@@RQQRRRROOOO3((           ^^/((	"
"\n\t\t\t\t    t3QR@ROQ@@@QR@R3tQR@@@@QOQ3tttt((     (t(/((//	"
"\n\t\t\t\t    (3OR@ROR@@RQR@Q33R@@@@RQOQ3t/(t3(t3t33t3t/tttt	"
"\n\t\t\t\t    tQR@R@@@@@QRRO3OR@@@@@@ROQQO33OO3(t333t3(^(3Ot	"
"\n\t\t\t\t    3@RR@@@@@ROQQR@@@@@@@R@RO3Q@RQQQ3(/O33QO(^^(t(	"
"\n\t\t\t\t    ORR@@@@@@QOQQ@@@@@@RQQ@R33QQQQQOt//3OtOOt(^^^/	"
"\n\t\t\t\t     QQRQR@@RO3QRRQ@@QR@@@@QttOOt//////(3t3Ot//^^/	"
"\n\t\t\t\t     3QQQR@RQOQR@RQOQ@@RRQRO(////^^^^///t(/33/((/^/	"
"\n\t\t\t\t     3RQQRRRQQR@@@ROR@@RQQROt///(/^^//tt3tttt(tOt^/	"
"\n\t\t\t\t     t3OOQRQOQR@@@QORRRQOQQ33(tOOO3(/O@@@Qtt/^OOO^/	"
"\n\t\t\t\t       3RQRQOQ@@@ROQQ3QQQRRQQO33tt33t(3OOO/((/(/t3	"
"\n\t\t\t\t        OQQQOR@RQOOQQ3QQQRRRQOO3333333t(/(tt^^(/3O	"
"\n\t\t\t\t         OOO3OOO33RRQQQQQOQOOQQOOQQOOO3((t(3RRt^/3	"
"\n\t\t\t\t         OOO33OO33RROOOQQ3OQOQQOOQQQQOt/(tttRR(^		"
"\n\t\t\t\t         OO3ttt33OR@RQQQQO3Q@OOQQOQOQOO3t3QOO3		"
"\n\t\t\t\t         QQO3ttttOR@QOQO3OOOQ@@RRQQQOO33O333			"
"\n\t\t\t\t         OQO3O333OR@QOQQOOOQQ@@@RQQRQQ3OO3O3			"
"\n\t\t\t\t         3RQQRRQOQ@@RQOOOOQRQRRRQQQOOOOQ33t			"
"\n\t\t\t\t         3QRRRRQO3Q@R@@@RRQRQQRQOOOOQQQQQO			"
"\n\t\t\t\t         3OO3O33O3OR@@@@@@RRRQQQQOOOO3ttt3			"
"\n\t\t\t\t         3t(ttt33QO3OQRRRQQQQQQQQQOQQQQO3			"
"\n\t\t\t\t         tO3tt33tQQQQOQ@@@RQQQRRQRRR@@QO				"
"\n\t\t\t\t         /tttt3ttORRQOOQQQ     @@@@@QOt(				"
"\n\t\t\t\t         ^(t3tt(tOROR@@@@R     @@@@ROt33				"
"\n\t\t\t\t         ^t3tt(/t3QOORR@@R     @@@@@@Qt				"
"\n\t\t\t\t         ^(t((///3t(//((OO     @@@RQQOt				"
"\n\t\t\t\t         ^(t(^//^/tt(//(33     RQ3t(//				"
"\n\t\t\t\t         ^/t(//^^^tO3t/(tt     OO3t(/^				"
"\n\t\t\t\t         ^/((((/(/(3Ot(//t     33((//^				"
"\n\t\t\t\t         ^t33t/(((/(t33t/(     (/(//t				"
"\n\t\t\t\t         tOO33t(tt/(3QQ3((     (/(t(3				"
"\n\t\t\t\t              OOO3ttt33O3    3(/^/tOt				"
"\n\t\t\t\t                ROtOQQQRO    3////^^t				"
"\n\t\t\t\t                  33R@@Q3    O///(((3				"
"\n\t\t\t\t                  33RRQQO    O/((333(/				"
"\n\t\t\t\t                  OOR@RQO    Ot(((t3t(/				"
"\n\t\t\t\t                              QOOO3OOOt(				",
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
"\n\t\t\t\t          OORRO                                      "
"\n\t\t\t\t          3ORRQ										"
"\n\t\t\t\t          OR@@R										"
"\n\t\t\t\t          Q@@@R										"
"\n\t\t\t\t          R@@@R										"
"\n\t\t\t\t          OQ@@3										"
"\n\t\t\t\t          3OR@3										"
"\n\t\t\t\t          33R@Q										"
"\n\t\t\t\t          R@@@@										"
"\n\t\t\t\t          @@@@@@										"
"\n\t\t\t\t          @@@@@@										"
"\n\t\t\t\t          @@@@@@										"
"\n\t\t\t\t          @@@@@@@									"
"\n\t\t\t\t          ORR@@@@									"
"\n\t\t\t\t          t3Q@@@@O									"
"\n\t\t\t\t          3OR@@@Q3t									"
"\n\t\t\t\t          OR@@@@R((/									"
"\n\t\t\t\t          3R@@@@@Ot									"
"\n\t\t\t\t          3R@@@@@@Q									"
"\n\t\t\t\t          O@@@@@@@O									"
"\n\t\t\t\t          Q@@@@@@@3									"
"\n\t\t\t\t          O@@@@@@RO									"
"\n\t\t\t\t          ORRRR@@@O									"
"\n\t\t\t\t          QQQQ3OOQO									"
"\n\t\t\t\t          3OOQOO3QO3									"
"\n\t\t\t\t        (33OQQOOOQQ3									"
"\n\t\t\t\t        tt3OQQQQOQOOt								"
"\n\t\t\t\t        OOOQQQO3OOOOQQQQO                        ^(	"
"\n\t\t\t\t        OOQR@@RRQQQQOOQQQOO                     ^(t	"
"\n\t\t\t\t        RR@@@@@RR@@@@RRQ3OQRQOOO3t(           ^^//t	"
"\n\t\t\t\t       Q@@@@@@RQR@@@@RRRQRRQOOO3tttt(       (/////^	"
"\n\t\t\t\t       R@@RRRRRQR@@@RQRRRRRQOQOt((t3(3  33tt(/(t((/	"
"\n\t\t\t\t      3RRRQQRRRQR@Ot3R@@@@ROOOQO33OQ3(tttO3t/^(3O3(	"
"\n\t\t\t\t     33R@ROR@@QR@R33QR@@@@ROOQQRROOOO(/t3333(^^tO3(	"
"\n\t\t\t\t     ttQ@@R@@@QRQt3Q@@@@@@@@33ORQQRQ3^^/Qt3Qt(^^^^t	"
"\n\t\t\t\t      Q@RR@@@@QRQR@@@@@@RORR3tOQt/^^/^^/tt333^^ ^^(	"
"\n\t\t\t\t      QRR@@@RROQQ@@@@@@RRQRR3tt3t/^^^^^^t((33^( ^^^	"
"\n\t\t\t\t       Q@@@@@QOQ@@R@@QR@@@@Rt//^/^^^^//((t(tt/(3O^^	"
"\n\t\t\t\t       ORQRRRQQQRRQQOR@RQOQQ3(t3OO3t(OQ@Q@3t/^OQOt/	"
"\n\t\t\t\t       ORRRRRQRR@@RQQR@QQQQQOt3O3333(3QRR@3/(^3t3((	"
"\n\t\t\t\t        QQQRQO@@@@@QQQQQQQQRQO33t333O33t//tt/^(/(3	"
"\n\t\t\t\t        OQRQOQ@@@@@QQR3QRQRRQROOOOOOOQO3((t(QO3^^t	"
"\n\t\t\t\t        3ORQOO@@@@RQQR3QRQOQQRQOOOQQOO3t(((/RRt^^3	"
"\n\t\t\t\t          QO33QORQOQQ@OOQQ3tQRQOQQQQQQQO33OQO33		"
"\n\t\t\t\t          QQO3OOQO3O@@OOQOO3O@QOQQQQQQOO3t3O3		"
"\n\t\t\t\t          OQ3tt3OO33Q@QQO3OQQOR@@RQQQOO3t3t3			"
"\n\t\t\t\t          OQQOttt333R@OOQQOO3ORR@RQQQOOt3O3t			"
"\n\t\t\t\t          QQQO3ttttOR@OO3OQQOOOQRQOOO33t33tt			"
"\n\t\t\t\t         ^tRRORRQO33QRQRRQQQQQQQOOO33333O3			"
"\n\t\t\t\t         ^(QRRR@@RQORRR@@@RRRQQQOO333ttt t			"
"\n\t\t\t\t         ^tORRRRRQOOR@R@@RQRQ3OO333O3333				"
"\n\t\t\t\t        ^^(33333333ttt33OQQ@@RQQQQQQQ3tt				"
"\n\t\t\t\t        ^^(3ttttttt3tt333OOO@RR@@@RQO3(t				"
"\n\t\t\t\t        ^^(t3OO33tt3QQR@QR@@QR@@@@@Q33				"
"\n\t\t\t\t       ^^^(((tt3tt(tOO^ ^^^tR@@@@@@@@3				"
"\n\t\t\t\t       ^^/(t(t3tt(/tO3/^^^ ^OR@@@RRQOt				"
"\n\t\t\t\t       ^^/(tt3O3(/^tt/(3t^^ (OQQ33(((				"
"\n\t\t\t\t       ^///(tt(((/^^t O3//t^ t3333t/(				"
"\n\t\t\t\t       ^(((3tt(//^^^t t/(QO/^/tttt(/					"
"\n\t\t\t\t        O33333t////^^/t///^^^ /33t33					"
"\n\t\t\t\t              ((//(//^t(((t3t ^t33t					"
"\n\t\t\t\t              3t(/t(((//(333t^^(t3t					"
"\n\t\t\t\t              QO33Ott3(t33OO3(/(ttt					"
"\n\t\t\t\t               OQOOO3Q33333O3(/(t333					"
"\n\t\t\t\t                         tttt(/(33t3(				"
"\n\t\t\t\t                         3t3tttt3RQOtO				"
"\n\t\t\t\t                         3t3t3t3ORQQOO				"
"\n\t\t\t\t                           OOOOOOO					",
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
"\n\t\t\t\t              OQQO                                   "
"\n\t\t\t\t              OQQQ									"
"\n\t\t\t\t              Q@@@									"
"\n\t\t\t\t              Q@@@									"
"\n\t\t\t\t              @@@@									"
"\n\t\t\t\t              OR@@									"
"\n\t\t\t\t              3Q@@tO									"
"\n\t\t\t\t              tO@ROQ									"
"\n\t\t\t\t             OQ@@@@Q									"
"\n\t\t\t\t             Q@@@@@Q									"
"\n\t\t\t\t              @@@@@@									"
"\n\t\t\t\t              @@@@@@									"
"\n\t\t\t\t              @@@@@@									"
"\n\t\t\t\t             3QRR@@@QQ								"
"\n\t\t\t\t             t3OQ@@@QQ								"
"\n\t\t\t\t              OQ@@@RO333								"
"\n\t\t\t\t              Q@@@@@3t/(								"
"\n\t\t\t\t              Q@@@@@Ot/t								"
"\n\t\t\t\t              O@@@@@@Q3O								"
"\n\t\t\t\t             tR@@@@@@R								"
"\n\t\t\t\t             tR@@@@@@Q								"
"\n\t\t\t\t             3R@RR@@@Q								"
"\n\t\t\t\t             3QRRQ@@@Q								"
"\n\t\t\t\t             OQQQOO3QQ								"
"\n\t\t\t\t            33OQQQ33QO33								"
"\n\t\t\t\t            33OO3Q3OQQ33								"
"\n\t\t\t\t            tt3333QRQO3t								"
"\n\t\t\t\t           OQQQ33t33Q@RRR3t    3t/(             /^/	"
"\n\t\t\t\t           QR@@RRQQOQRRRRQOOO33O33t/3          ^^^/	"
"\n\t\t\t\t         QQR@@@@@RRRQQOOOQRRQ3O3ttt((       3/^////	"
"\n\t\t\t\t         @@@@@@@R@@@@@@ROQRRQOOOt(t3Ott3t33tt(/tttt	"
"\n\t\t\t\t        Q@@RR@@RRR@@@@RRRRRROOQQO33OO3(3tt3tt//t33t	"
"\n\t\t\t\t       3OR@QQQRRQR@ROOQR@@@RO3OQRQRQOt^/tO(O3(^^/tt	"
"\n\t\t\t\t       (3Q@ORRRRQ@R3tOR@@@@RO33QQQQQQ/^^(O(33t/  ^^	"
"\n\t\t\t\t       3O@@R@@ROQRO3O@@@@@@@QttOO(^^^/^^/t(t3t/^^^^	"
"\n\t\t\t\t       QRRQ@@@QQ@Q3OR@@@@@RRQt//^/^^ ^//^tt/3t/(/^^	"
"\n\t\t\t\t       QQR@@@RRR@RQR@@@@@QQRQ/////^^^^/tttt(t((tO3^	"
"\n\t\t\t\t       33@@R@@QQQR@@@@RRR@QRQ3(333O3((ORRRR((/^OQO/	"
"\n\t\t\t\t         RQR@RQ3QR@QRQQ@RQOQQO33tt333tt3ttt(/^^(^tt	"
"\n\t\t\t\t         QR@RRQOQQRQQOR@QQOQROO3333333O3t//tt////t3	"
"\n\t\t\t\t         QORRRQQRR@@RORRRQQQRRQO3OOOOOO3((((O@Q/^/	"
"\n\t\t\t\t           RQOOQ@@@@@ORQOQQQQQORQOQQQQO3tt3OQRQt/t	"
"\n\t\t\t\t           RQOQR@@@@@QRQOQQO3RQRQQOOQRRO333QQO33		"
"\n\t\t\t\t           ROOOR@@@@RQQROOOQO3O@QQRRROOO3333t3		"
"\n\t\t\t\t           QO33QRQ@@QQQ@OOOOQO3QRRRRRQQO3t(tt3		"
"\n\t\t\t\t           RO3t33OQO33R@QOQOOOQQQOQRQO333t3t			"
"\n\t\t\t\t           RQO3tt3O333Q@ROOOQQQOOOOOO333ttt3			"
"\n\t\t\t\t           RQOO33t333OOR@QOO33OOOO333333t3tt			"
"\n\t\t\t\t           RQQQRQO3t33OORQQQQOQQQQOO3tttttt			"
"\n\t\t\t\t           ORRR@@@RO3tt3RRRR@@@@RQ3t3tt((			"
"\n\t\t\t\t           OQQR@RRQOttt3QRR@@@@RRQQ33ttt				"
"\n\t\t\t\t           33t3333tt(tttQ@@RRQRRR@@Q33t				"
"\n\t\t\t\t           tO3t33ttt    ORRO3333tORQ3tt				"
"\n\t\t\t\t           (tt33tt(t    (t(tO3t333QRQ				"
"\n\t\t\t\t           (OO3t(/t3     OQQRR@@@@QOO				"
"\n\t\t\t\t           /333t//t3     ORR@@@RR@@33				"
"\n\t\t\t\t           t((((/^^3      ORQt(^^^/t3				"
"\n\t\t\t\t            t((//^^/       OO(/^  ^^t				"
"\n\t\t\t\t            tt((//^^       t3(//^^^^/				"
"\n\t\t\t\t             t(((/^^^t     (^tOQt//^^/				"
"\n\t\t\t\t             O3(tO(3//(t   /^/t3(3Ot^^^				"
"\n\t\t\t\t              OO3Ot3t(OO   //(tt((//^^ /3			"
"\n\t\t\t\t                          O(((33(//(t(^^(			"
"\n\t\t\t\t                          Q3tt33t/(t33/^ t			"
"\n\t\t\t\t                          O33OOOOt(((/^^^^3			"
"\n\t\t\t\t                                 Ot(/(t((/(			"
"\n\t\t\t\t                                 O3(((3t(/t			"
"\n\t\t\t\t                                   O333OOO3			",
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
"\n\t\t\t\t               QQ                                    "
"\n\t\t\t\t             OOQRQO									"
"\n\t\t\t\t               R@RQ									"
"\n\t\t\t\t               @@@R									"
"\n\t\t\t\t               @@@@									"
"\n\t\t\t\t               @@@R									"
"\n\t\t\t\t               R@@O3									"
"\n\t\t\t\t               3Q@33									"
"\n\t\t\t\t               R@@@@									"
"\n\t\t\t\t               @@@@@									"
"\n\t\t\t\t             R@@@@@@Q								"
"\n\t\t\t\t             R @@@@@@								"
"\n\t\t\t\t               @@@@@@								"
"\n\t\t\t\t               @@@@@@O								"
"\n\t\t\t\t               OR@@@@RO								"
"\n\t\t\t\t               OR@@@RQ3								"
"\n\t\t\t\t               @@@@RO33t								"
"\n\t\t\t\t               @@@@@Qt((								"
"\n\t\t\t\t               @@@@@@Ot3								"
"\n\t\t\t\t             tO@@@@@@@Q								"
"\n\t\t\t\t             3Q@@@@@@@O								"
"\n\t\t\t\t             tQ@@@@@@@3								"
"\n\t\t\t\t             3Q@RR@@@RO								"
"\n\t\t\t\t             OORRO@R@RO								"
"\n\t\t\t\t             OOOQ3O3OQOt								"
"\n\t\t\t\t             3OQQOO3QQO3								"
"\n\t\t\t\t            (3OOOO3ORQO3								"
"\n\t\t\t\t            (3OQQRQQO333								"
"\n\t\t\t\t            ttt33QQRQQQO(3							"
"\n\t\t\t\t           ORO3333QR@@@RO3OO							"
"\n\t\t\t\t          QR@@@RRQQQRRRRRRQQO3t                 /((	"
"\n\t\t\t\t         Q@@@@@@@RQOOOQQRRQO3OO3t^            ^^/(	"
"\n\t\t\t\t        R@@@@@@@R@@RRRQ3OQQQO33ttt(         /^//^/	"
"\n\t\t\t\t       OR@R@@@RR@@@@@R@RRRRQOO3//t3t/33(3ttt//(t((	"
"\n\t\t\t\t       3R@RQRRRQR@@@@RR@@RRQOQ3tt3O3(tt(33((^/33tt	"
"\n\t\t\t\t       3Q@RR@@@Q@@RO3Q@@@@@QOQRRQOQ3(//O3OOt/^^t3t	"
"\n\t\t\t\t       Q@@R@@@RQ@@O3QR@@@@@Q3ORQQQQt/^/333Ott^^//(	"
"\n\t\t\t\t       RRR@@@RQR@R3OR@@@@@@O33Q3((/////(tt33t/^^^(	"
"\n\t\t\t\t       OQ@@@@@Q@@QOR@@@@@RROt((//^^^//^/t/tO(/(/^^	"
"\n\t\t\t\t       3Q@@R@RQ@RRR@@@@@RQRO(////^^/^(((3(t3((tt^^	"
"\n\t\t\t\t        QRR@@@QQQ@@@@@RR@RROt(tOOO3/OO@RRtt//(OO3^	"
"\n\t\t\t\t        QQR@RROOQQQQ@RR@QOQQOO33tt3t(t333t^(//^ttt	"
"\n\t\t\t\t         QQR@ROQQQQQRQ@@OOQRO333333333t(^tt(^/((33	"
"\n\t\t\t\t         ORRQOQR@@@@QQRRQQR@RQOOOOOOOO3(((/Q@O^^		"
"\n\t\t\t\t         ORQOOQ@@@@@QQROQQR@RRQQOQQQOOt(t33ORO(/		"
"\n\t\t\t\t         ORQ3OQ@@@@@QQ@3QRQQQQQQQOQQQQO33OQQQ3t		"
"\n\t\t\t\t         ORQ3tORRR@RQQ@QQQQ3QRRQRQQQQQOO3O3tt		"
"\n\t\t\t\t         OQQ3t3OOQRQOQ@ROOQOORRQQQRQOOO333ttt		"
"\n\t\t\t\t         QQOO3tt3OOO3QRRQQQRROOQR@ROO333t333t		"
"\n\t\t\t\t        3ORQQQOO333OOR@@QQQQOOOQQQRQOO33tt3t			"
"\n\t\t\t\t        t3QQQRRQO333OOR@QOQRQOOOQQQO33(t3ttt			"
"\n\t\t\t\t         33QR@@@RR33t3OQRQO33OOO3333O3ttt3			"
"\n\t\t\t\t         (t333OOO    333RRRR@@R@@QQ33tttt			"
"\n\t\t\t\t         /3333333    333RRR@@@@RQ33tt(t(t			"
"\n\t\t\t\t         /3333333    3O3O@@@@RRRRRQO3tt				"
"\n\t\t\t\t         /3OO3O      3333R@@@R@@@@@O3tt				"
"\n\t\t\t\t          t(t3O3t    t33tttt3O33(tQOt				"
"\n\t\t\t\t          tt(t33t    ((t(tOOQO33QQ3					"
"\n\t\t\t\t          ((/t333    (ttt3QRROQR@@R					"
"\n\t\t\t\t          t(tttt3    (t3t3tQ@@@@R@@					"
"\n\t\t\t\t           t((ttt(    333t/(RQ3(/^^/3				"
"\n\t\t\t\t           3(ttt3((t  33O(/(OOt(^^ ^(				"
"\n\t\t\t\t           3ttOt3t3O    3^/t33((/^^^^				"
"\n\t\t\t\t             OOOOO      t/t3OOOQROt^ ^t				"
"\n\t\t\t\t                        t33OQ3OR@O(//^^				"
"\n\t\t\t\t                        O3O3OOtttt3QO^^^3			"
"\n\t\t\t\t                        QOQOQQO3tt3t(^ ^3			"
"\n\t\t\t\t                                O(/(t3( /			"
"\n\t\t\t\t                                 (/(/((/((			"
"\n\t\t\t\t                                 3((^t(/(^			"
"\n\t\t\t\t                                  OO33O33t			"
};