const { EmbedBuilder } = require('discord.js');
//...
      return {embeds: [new EmbedBuilder()
         .setColor(colors.primary)
         //...
         .setFooter({ text: `Use ${prefix}help for support`})
      ]}
//...
      return {embeds: [new EmbedBuilder()
         //...
         .setFooter({ text: `Use ${prefix}help for support`})
      ]}
//...
      return {embeds: [new EmbedBuilder()
         //...
         .setFooter({ text: `Use ${prefix}help for support`})
      ]}
